# Generated by Django 3.2.10 on 2023-01-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventDefinition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patientinfo',
            table='vPatientInfo',
        ),
    ]
