# Generated by Django 3.2.10 on 2023-01-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventDefinition', '0003_auto_20230112_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examreporttext',
            fields=[
                ('orderNo', models.IntegerField(db_column='OrderNo', primary_key=True, serialize=False)),
                ('reportTime', models.DateTimeField(db_column='reportTime')),
                ('reportDiag', models.CharField(db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='reportDiag', max_length=1500)),
                ('reportText', models.TextField(db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='reportText')),
            ],
            options={
                'db_table': 'examReportText',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medorder',
            fields=[
                ('visitNo', models.IntegerField(db_column='VisitNo')),
                ('orderNo', models.IntegerField(db_column='OrderNo', primary_key=True, serialize=False)),
                ('execTime', models.DateTimeField(blank=True, db_column='execTime', null=True)),
                ('visitZone', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='visitZone', max_length=1, null=True)),
                ('visitGroup', models.IntegerField(blank=True, db_column='visitGroup', null=True)),
                ('source', models.IntegerField()),
                ('medtype', models.SmallIntegerField(db_column='medType')),
                ('trancode', models.CharField(db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='tranCode', max_length=1)),
            ],
            options={
                'db_table': 'medOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medtypeset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medtype', models.SmallIntegerField(db_column='MedType')),
                ('typename', models.CharField(db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='TypeName', max_length=100)),
            ],
            options={
                'db_table': 'medTypeSet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitrecord',
            fields=[
                ('visitno', models.IntegerField(db_column='VisitNo')),
                ('aicno', models.IntegerField(db_column='aicNo', primary_key=True, serialize=False)),
                ('visitdate', models.DateTimeField(db_column='visitDate')),
                ('visitzone', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='visitZone', max_length=1, null=True)),
                ('visittype', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='visitType', max_length=2, null=True)),
                ('visitseqno', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='visitSeqNo', max_length=4, null=True)),
                ('sourcetype', models.SmallIntegerField(blank=True, db_column='sourceType', null=True)),
                ('sourceno', models.SmallIntegerField(blank=True, db_column='sourceNo', null=True)),
                ('divno', models.SmallIntegerField(blank=True, db_column='divNo', null=True)),
                ('visitstatus', models.CharField(blank=True, db_collation='Chinese_Taiwan_Stroke_CS_AS', db_column='visitStatus', max_length=1, null=True)),
                ('outdate', models.DateTimeField(blank=True, db_column='outDate', null=True)),
                ('outtype', models.SmallIntegerField(blank=True, db_column='outType', null=True)),
            ],
            options={
                'db_table': 'visitRecord',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
