# Generated by Django 3.2.10 on 2023-01-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventDefinition', '0004_auto_20230112_1009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitrecord',
            table='fvisitRecord',
        ),
    ]
