# Generated by Django 3.2.10 on 2023-01-12 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventDefinition', '0006_alter_visitrecord_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitrecord',
            options={'managed': True},
        ),
    ]
