# Generated by Django 3.2.10 on 2023-01-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventDefinition', '0007_alter_visitrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrecord',
            name='aicno',
            field=models.IntegerField(db_column='aicNo', default=0, primary_key=True, serialize=False),
        ),
    ]
