# Generated by Django 3.2.10 on 2023-01-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventDefinition', '0008_alter_visitrecord_aicno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medtypeset',
            table='vMedTypeSet',
        ),
    ]
